// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlphvpkdeoatmvzkntpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpscGh2cGtkZW9hdG12emtudHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjA2MzcsImV4cCI6MjA2NzIzNjYzN30.v2s_cZulb57g8u-XrdOZrY1T98l3Mlld5YbeU4d8Jfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});